export {
	useLocation,
	useNavigate,
	useFetcher,
	useFetchers,
	useActionData,
	useFormAction,
	useOutlet,
	useOutletContext,
	useParams,
	useHref,
	Link,
	LinkProps,
	Form,
	FormProps,
	ScrollRestoration,
	ScrollRestorationProps,
	Outlet,
	OutletProps,
} from 'react-router-dom';
export { Index } from '../types/indexFile';
